/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Subject = IDL.Variant({
  'logicalReasoning' : IDL.Null,
  'math' : IDL.Null,
  'computerConcepts' : IDL.Null,
  'english' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat32,
  'topic' : IDL.Text,
  'subject' : Subject,
  'difficulty' : Difficulty,
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat32,
  'options' : IDL.Vec(IDL.Text),
});
export const StudyResource = IDL.Record({
  'id' : IDL.Nat32,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'subject' : Subject,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfileView = IDL.Record({ 'name' : IDL.Text });
export const UserStatsView = IDL.Record({
  'subjectPerformance' : IDL.Vec(
    IDL.Tuple(
      Subject,
      IDL.Record({ 'attempted' : IDL.Nat32, 'correct' : IDL.Nat32 }),
    )
  ),
  'topicCompletion' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'user' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func([Question], [IDL.Nat32], []),
  'addStudyResource' : IDL.Func([StudyResource], [IDL.Nat32], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestionsBySubject' : IDL.Func([Subject], [IDL.Vec(Question)], ['query']),
  'getRandomQuestions' : IDL.Func([IDL.Nat32], [IDL.Vec(Question)], ['query']),
  'getResourcesBySubject' : IDL.Func(
      [Subject],
      [IDL.Vec(StudyResource)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([], [IDL.Opt(UserStatsView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTopicComplete' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startExamSession' : IDL.Func([IDL.Vec(IDL.Nat32)], [IDL.Nat32], []),
  'submitExamSession' : IDL.Func(
      [
        IDL.Nat32,
        IDL.Vec(
          IDL.Record({ 'answerIndex' : IDL.Nat32, 'questionId' : IDL.Nat32 })
        ),
        IDL.Nat32,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Subject = IDL.Variant({
    'logicalReasoning' : IDL.Null,
    'math' : IDL.Null,
    'computerConcepts' : IDL.Null,
    'english' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat32,
    'topic' : IDL.Text,
    'subject' : Subject,
    'difficulty' : Difficulty,
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat32,
    'options' : IDL.Vec(IDL.Text),
  });
  const StudyResource = IDL.Record({
    'id' : IDL.Nat32,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'subject' : Subject,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfileView = IDL.Record({ 'name' : IDL.Text });
  const UserStatsView = IDL.Record({
    'subjectPerformance' : IDL.Vec(
      IDL.Tuple(
        Subject,
        IDL.Record({ 'attempted' : IDL.Nat32, 'correct' : IDL.Nat32 }),
      )
    ),
    'topicCompletion' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'user' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func([Question], [IDL.Nat32], []),
    'addStudyResource' : IDL.Func([StudyResource], [IDL.Nat32], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileView)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestionsBySubject' : IDL.Func(
        [Subject],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getRandomQuestions' : IDL.Func(
        [IDL.Nat32],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getResourcesBySubject' : IDL.Func(
        [Subject],
        [IDL.Vec(StudyResource)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([], [IDL.Opt(UserStatsView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTopicComplete' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startExamSession' : IDL.Func([IDL.Vec(IDL.Nat32)], [IDL.Nat32], []),
    'submitExamSession' : IDL.Func(
        [
          IDL.Nat32,
          IDL.Vec(
            IDL.Record({ 'answerIndex' : IDL.Nat32, 'questionId' : IDL.Nat32 })
          ),
          IDL.Nat32,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };