/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Question {
  'id' : number,
  'topic' : string,
  'subject' : Subject,
  'difficulty' : Difficulty,
  'explanation' : string,
  'text' : string,
  'correctAnswerIndex' : number,
  'options' : Array<string>,
}
export interface StudyResource {
  'id' : number,
  'url' : string,
  'title' : string,
  'subject' : Subject,
  'description' : string,
}
export type Subject = { 'logicalReasoning' : null } |
  { 'math' : null } |
  { 'computerConcepts' : null } |
  { 'english' : null };
export interface UserProfile { 'name' : string }
export interface UserProfileView { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStatsView {
  'subjectPerformance' : Array<
    [Subject, { 'attempted' : number, 'correct' : number }]
  >,
  'topicCompletion' : Array<[string, boolean]>,
  'user' : Principal,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addQuestion' : ActorMethod<[Question], number>,
  'addStudyResource' : ActorMethod<[StudyResource], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestionsBySubject' : ActorMethod<[Subject], Array<Question>>,
  'getRandomQuestions' : ActorMethod<[number], Array<Question>>,
  'getResourcesBySubject' : ActorMethod<[Subject], Array<StudyResource>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'getUserStats' : ActorMethod<[], [] | [UserStatsView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTopicComplete' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startExamSession' : ActorMethod<[Uint32Array], number>,
  'submitExamSession' : ActorMethod<
    [number, Array<{ 'answerIndex' : number, 'questionId' : number }>, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];