/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StudyResource {
    id: number;
    url: string;
    title: string;
    subject: Subject;
    description: string;
}
export interface UserProfileView {
    name: string;
}
export interface UserStatsView {
    subjectPerformance: Array<[Subject, {
            attempted: number;
            correct: number;
        }]>;
    topicCompletion: Array<[string, boolean]>;
    user: Principal;
}
export interface Question {
    id: number;
    topic: string;
    subject: Subject;
    difficulty: Difficulty;
    explanation: string;
    text: string;
    correctAnswerIndex: number;
    options: Array<string>;
}
export interface UserProfile {
    name: string;
}
export enum Difficulty {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum Subject {
    logicalReasoning = "logicalReasoning",
    math = "math",
    computerConcepts = "computerConcepts",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addQuestion(question: Question): Promise<number>;
    addStudyResource(resource: StudyResource): Promise<number>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllUserProfiles(): Promise<Array<UserProfileView>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getQuestionsBySubject(subject: Subject): Promise<Array<Question>>;
    getRandomQuestions(count: number): Promise<Array<Question>>;
    getResourcesBySubject(subject: Subject): Promise<Array<StudyResource>>;
    getUserProfile(user: Principal): Promise<UserProfileView | null>;
    getUserStats(): Promise<UserStatsView | null>;
    isCallerAdmin(): Promise<boolean>;
    markTopicComplete(topic: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startExamSession(questionIds: Uint32Array): Promise<number>;
    submitExamSession(sessionId: number, answers: Array<{
        answerIndex: number;
        questionId: number;
    }>, timeSpent: number): Promise<void>;
}
import type { Difficulty as _Difficulty, Question as _Question, StudyResource as _StudyResource, Subject as _Subject, UserProfileView as _UserProfileView, UserRole as _UserRole, UserStatsView as _UserStatsView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addQuestion(arg0: Question): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(to_candid_Question_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(to_candid_Question_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addStudyResource(arg0: StudyResource): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudyResource(to_candid_StudyResource_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudyResource(to_candid_StudyResource_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsBySubject(arg0: Subject): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsBySubject(to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsBySubject(to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRandomQuestions(arg0: number): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRandomQuestions(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRandomQuestions(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesBySubject(arg0: Subject): Promise<Array<StudyResource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesBySubject(to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesBySubject(to_candid_Subject_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStats(): Promise<UserStatsView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStats();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStats();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markTopicComplete(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTopicComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTopicComplete(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async startExamSession(arg0: Uint32Array): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.startExamSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startExamSession(arg0);
            return result;
        }
    }
    async submitExamSession(arg0: number, arg1: Array<{
        answerIndex: number;
        questionId: number;
    }>, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitExamSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitExamSession(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Difficulty_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StudyResource_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyResource): StudyResource {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatsView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatsView): UserStatsView {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserStatsView]): UserStatsView | null {
    return value.length === 0 ? null : from_candid_UserStatsView_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    topic: string;
    subject: _Subject;
    difficulty: _Difficulty;
    explanation: string;
    text: string;
    correctAnswerIndex: number;
    options: Array<string>;
}): {
    id: number;
    topic: string;
    subject: Subject;
    difficulty: Difficulty;
    explanation: string;
    text: string;
    correctAnswerIndex: number;
    options: Array<string>;
} {
    return {
        id: value.id,
        topic: value.topic,
        subject: from_candid_Subject_n17(_uploadFile, _downloadFile, value.subject),
        difficulty: from_candid_Difficulty_n19(_uploadFile, _downloadFile, value.difficulty),
        explanation: value.explanation,
        text: value.text,
        correctAnswerIndex: value.correctAnswerIndex,
        options: value.options
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    url: string;
    title: string;
    subject: _Subject;
    description: string;
}): {
    id: number;
    url: string;
    title: string;
    subject: Subject;
    description: string;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        subject: from_candid_Subject_n17(_uploadFile, _downloadFile, value.subject),
        description: value.description
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subjectPerformance: Array<[_Subject, {
            attempted: number;
            correct: number;
        }]>;
    topicCompletion: Array<[string, boolean]>;
    user: Principal;
}): {
    subjectPerformance: Array<[Subject, {
            attempted: number;
            correct: number;
        }]>;
    topicCompletion: Array<[string, boolean]>;
    user: Principal;
} {
    return {
        subjectPerformance: from_candid_vec_n27(_uploadFile, _downloadFile, value.subjectPerformance),
        topicCompletion: value.topicCompletion,
        user: value.user
    };
}
function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Subject, {
        attempted: number;
        correct: number;
    }]): [Subject, {
        attempted: number;
        correct: number;
    }] {
    return [
        from_candid_Subject_n17(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logicalReasoning: null;
} | {
    math: null;
} | {
    computerConcepts: null;
} | {
    english: null;
}): Subject {
    return "logicalReasoning" in value ? Subject.logicalReasoning : "math" in value ? Subject.math : "computerConcepts" in value ? Subject.computerConcepts : "english" in value ? Subject.english : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): Difficulty {
    return "easy" in value ? Difficulty.easy : "hard" in value ? Difficulty.hard : "medium" in value ? Difficulty.medium : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyResource>): Array<StudyResource> {
    return value.map((x)=>from_candid_StudyResource_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Subject, {
        attempted: number;
        correct: number;
    }]>): Array<[Subject, {
        attempted: number;
        correct: number;
    }]> {
    return value.map((x)=>from_candid_tuple_n28(_uploadFile, _downloadFile, x));
}
function to_candid_Difficulty_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Question_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Question): _Question {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_StudyResource_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyResource): _StudyResource {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    topic: string;
    subject: Subject;
    difficulty: Difficulty;
    explanation: string;
    text: string;
    correctAnswerIndex: number;
    options: Array<string>;
}): {
    id: number;
    topic: string;
    subject: _Subject;
    difficulty: _Difficulty;
    explanation: string;
    text: string;
    correctAnswerIndex: number;
    options: Array<string>;
} {
    return {
        id: value.id,
        topic: value.topic,
        subject: to_candid_Subject_n3(_uploadFile, _downloadFile, value.subject),
        difficulty: to_candid_Difficulty_n5(_uploadFile, _downloadFile, value.difficulty),
        explanation: value.explanation,
        text: value.text,
        correctAnswerIndex: value.correctAnswerIndex,
        options: value.options
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    url: string;
    title: string;
    subject: Subject;
    description: string;
}): {
    id: number;
    url: string;
    title: string;
    subject: _Subject;
    description: string;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        subject: to_candid_Subject_n3(_uploadFile, _downloadFile, value.subject),
        description: value.description
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    logicalReasoning: null;
} | {
    math: null;
} | {
    computerConcepts: null;
} | {
    english: null;
} {
    return value == Subject.logicalReasoning ? {
        logicalReasoning: null
    } : value == Subject.math ? {
        math: null
    } : value == Subject.computerConcepts ? {
        computerConcepts: null
    } : value == Subject.english ? {
        english: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
} {
    return value == Difficulty.easy ? {
        easy: null
    } : value == Difficulty.hard ? {
        hard: null
    } : value == Difficulty.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
